version: '3'

services:
  countries:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./countries:/usr/src/app/
    ports:
      - 8000:8000

  pgadmin4:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./db-data:/pgadmin4/servers.json
    ports:
      - "5050:80"

  countries-postgres:
    container_name: countries-postgres
    image: postgres:12-alpine
    volumes:
      - ./country_db_data:/var/lib/admin_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=countries_api_db
    ports:
      - "5432:5432"